name: Everyday

on: [push]
#   schedule:
#     - cron: "0 0 * * *"
    
jobs:
      
  primerjob:
    name: descargar proyecto
    runs-on: ubuntu-latest
    steps:
      - name: Download a file
        uses: carlosperate/download-file-action@v1
        with:
            file-url: 'https://developer.mozilla.org/es/docs/Web/HTML'
            file-name: 'file'
            location: './new_folder'
          
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: public
          teardown: 'true'
          build: |
            npm install
            npm run build
