name: Everyday

on: [push]
#   schedule:
#     - cron: "0 0 * * *"
    
jobs:
  primerjob:
    name: descargar proyecto
    runs-on: ubuntu-latest
    steps:
      - name: Download a file
        id: download-poetry-simple
        uses: carlosperate/download-file-action@v1
        with:
          file-url: 'https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py'
          
      - run: echo "The file was downloaded to ${{ steps.download-poetry-simple.outputs.file-path }}"
          
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: public
          teardown: 'true'
          build: |
            npm install
            npm run build
