name: Everyday

on: [push]
#   schedule:
#     - cron: "0 0 * * *"
    
jobs:
  primerjob:
    name: descargar proyecto
    runs-on: ubuntu-latest
    steps:
      - name: Download a file
        uses: suisei-cn/actions-download-file@v1
        id: downloadfile  # Remember to give an ID if you need the output filename
        with:
            url: "https://cdn.jsdelivr.net/npm/workbox-sw@5.1.3/build/workbox-sw.min.js"
            target: public/
          
      - run: echo "The file was downloaded to ${{ steps.download-poetry-simple.outputs.file-path }}"
          
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: public
          teardown: 'true'
          build: |
            npm install
            npm run build
