name: Everyday

on: [push]
#   schedule:
#     - cron: "0 0 * * *"
    
jobs:
      
  primerjob:
    name: descargar proyecto
    runs-on: ubuntu-latest
    steps:
      - name: Download a file
        uses: carlosperate/download-file-action@v1
        with:
            file-url: 'https://github.com/carlosperate/download-file-action/archive/refs/tags/v1.0.3.tar.gz'
            file-name: 'new_filename.tar.gz'
            location: './new_folder'
          
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: public
          teardown: 'true'
          build: |
            npm install
            npm run build
