name: Everyday

on:
  push:
    branches: download_and_share_file
  schedule:
    - cron: "0 0 * * *"
    
jobs:
      
  primerjob:
    name: descargar proyecto
    runs-on: ubuntu-latest
    steps:
      - uses: suisei-cn/actions-download-file@v1
        name: Download the file
        with:
            url: "https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Informe_Comunicacion_20210127.ods"
            target: public/
          
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: public
          teardown: 'true'
          build: |
            npm install
            npm run build
